/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rueda;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
/**
 *
 * @author Usuario
 */
public class RuedaVolumen extends javax.swing.JPanel {

    /**
     * Creates new form RuedaVolumen
     */
    private double rotacion=0.0;
    private javax.swing.ImageIcon icono;
    private javax.swing.ImageIcon icono2;
    public RuedaVolumen() {
        initComponents();
    }
    public void girar(double giro){
        if((rotacion+giro<2.5)&&(rotacion+giro>-2.5 )){
        rotacion+=giro;
        repaint();
        }
    }
    public double getRotacion(){
        return rotacion;
    }
    @Override
     public void paint(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        
        // AffineTransform realiza el giro, usando como eje de giro el centro
        // de la foto (width/2, height/2) y el angulo que indica el atributo
        // rotacion.
        AffineTransform aux = AffineTransform.getRotateInstance(0, 
                icono2.getIconWidth()/2, icono2.getIconHeight()/2);
        AffineTransform tx = AffineTransform.getRotateInstance(rotacion, 
                icono.getIconWidth()/2, icono.getIconHeight()/2);
        
        // dibujado con la AffineTransform de rotacion
        g2d.drawImage(icono.getImage(), tx, this);
        g2d.drawImage(icono2.getImage(), aux, this);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setToolTipText("");

        jPanel2.setLayout(null);

        icono2=new javax.swing.ImageIcon(getClass().getResource("/sonido/Sin título-4.png")); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sonido/Sin título-4.png"))); // NOI18N
        jLabel3.setIcon(icono2);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 450, 450);

        icono=new javax.swing.ImageIcon(getClass().getResource("/sonido/Sin título-3.png")); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sonido/Sin título-3.png"))); // NOI18N
        jLabel2.setIcon(icono);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 450, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
