/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rueda;
import java.awt.Graphics;
import java.awt.Graphics2D;
/**
 *
 * @author i62cumuj
 */
public class Rueda extends javax.swing.JPanel {

    /**
     * Creates new form Rueda
     */
    private double rotation=0.0;
    private javax.swing.ImageIcon icon;
    public Rueda() {
        initComponents();

    }
    public void rot(double rad){
        rotation+=rad;
        paintComponent();
    }
    
     @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g;
                g2.rotate(rotation, jLabel3.getWidth() / 2, jLabel3.getHeight() / 2);
                g2.drawImage(icon.getImage(), 0, 0, null);
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microondas/microondas_potencia1.jpg"))); // NOI18N

        jPanel2.setLayout(null);

        icon=new javax.swing.ImageIcon(getClass().getResource("/microondas/ruedaMicro.png"));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microondas/ruedaMicro.png"))); // NOI18N
        jLabel3.setIcon(icon);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 0, 400, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microondas/microondas_potencia1.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
